import type { DemoFeatureRegistryItem } from '@/types/hr';

export const DEMO_FEATURES: DemoFeatureRegistryItem[] = [
  {
    id: 'FEAT-HR-001',
    module: 'HR & Employees',
    feature_name: 'Employee Master & Directory',
    description: 'Centralized directory for office and site personnel with sequential EMP-XXXX identification and full employment lifecycle tracking.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees',
    demo_enabled: true,
    notes: 'Configured with official company staff details and demo technician profiles.',
  },
  {
    id: 'FEAT-HR-002',
    module: 'HR & Employees',
    feature_name: 'Employee 360 Profile View',
    description: 'Unified personnel overview with role-filtered tabs dynamically showing only permitted sections based on authenticated user credentials.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/EMP-UUID-0007',
    demo_enabled: true,
    notes: 'Demonstrates K. Suresh Lead AV Site Technician record with site deployment history.',
  },
  {
    id: 'FEAT-HR-003',
    module: 'Attendance & Time',
    feature_name: 'Office & Site Attendance Board',
    description: 'Dual-mode attendance tracking supporting in-office check-ins and client-site deployments (e.g. Swan Technologies Phase 2 site).',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/attendance',
    demo_enabled: true,
    notes: 'Managed by Manisha (Office Assistant) with full roster logging authority.',
  },
  {
    id: 'FEAT-HR-004',
    module: 'Attendance & Time',
    feature_name: 'Audited Attendance Correction Workflow',
    description: 'Formal correction request and approval cycle preventing silent overwrites of historical time records.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/attendance',
    demo_enabled: true,
    notes: 'Logs requested status, original status, reason, requested_by, and approver audit.',
  },
  {
    id: 'FEAT-HR-005',
    module: 'Payroll & Compensation',
    feature_name: 'Confidential Salary Structures & Revision History',
    description: 'Multi-component Indian payroll structures (Basic, HRA, Conveyance, Allowances, PF, ESI, PT, TDS) with immutable historical revisions.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/payroll',
    demo_enabled: true,
    notes: 'Strictly restricted to Accounts (Hemalath) and Managing Director (Borra Narsimulu).',
  },
  {
    id: 'FEAT-HR-006',
    module: 'Payroll & Compensation',
    feature_name: 'Monthly Payroll Processing & Payout Batch',
    description: 'Monthly compensation calculation integrating working days, paid leaves, statutory deductions, and payout batch reconciliation.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/payroll',
    demo_enabled: true,
    notes: 'Demonstrates August 2026 closed payout and September 2026 reviewed batch.',
  },
  {
    id: 'FEAT-HR-007',
    module: 'Payroll & Compensation',
    feature_name: 'Sequential Payslip Engine & PDF Layout',
    description: 'Sequential collision-safe payslip numbers (PAY/26-27/0001) with clean printable document preview.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/payslips',
    demo_enabled: true,
    notes: 'Formatted with ICON TECH PRO legal entity headers, earnings, and statutory deductions.',
  },
  {
    id: 'FEAT-HR-008',
    module: 'HR Documents',
    feature_name: 'Document Vault & Sensitivity Classification',
    description: 'Secure employee document repository categorized by NORMAL, CONFIDENTIAL, FINANCIAL, and RESTRICTED tiers.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/documents',
    demo_enabled: true,
    notes: 'Enforces server-side authorization blocking unauthorized access to financial documents.',
  },
  {
    id: 'FEAT-HR-009',
    module: 'HR Documents',
    feature_name: 'Offer Letter Generator & Lifecycle',
    description: 'Employment offer drafting with sequential OFF/26-27/0001 numbering, CTC schedule, and acceptance status tracking.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/employees/documents',
    demo_enabled: true,
    notes: 'Contains formal draft, issued, accepted, and withdrawn workflow states.',
  },
  {
    id: 'FEAT-RBAC-010',
    module: 'Security & Access Control',
    feature_name: 'Segregation of Duties & Field-Level Masking',
    description: 'Strict role authorization: Manisha allowed attendance management but blocked from salary/payroll; Accounts allowed payroll; Sales blocked from HR confidential records.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/settings/users',
    demo_enabled: true,
    notes: 'Enforced at server action level via requireRole() and database RLS.',
  },
  {
    id: 'FEAT-SYNC-011',
    module: 'Local Demo Synchronization',
    feature_name: 'Dynamic Demo Feature Registry & What\'s Updated Page',
    description: 'Automated release registry connecting live ERP capabilities directly to the local presentation dashboard without manual static hardcoding.',
    status: 'ACTIVE',
    version: 'v7.0',
    added_date: '2026-09-16',
    last_updated: '2026-09-16T10:00:00Z',
    demo_route: '/dashboard/demo-updates',
    demo_enabled: true,
    notes: 'Enables presenters to demonstrate completed features with 1-click navigation.',
  },
  {
    id: 'FEAT-OPS-012',
    module: 'Quotation Workflow',
    feature_name: 'Mandatory Review Gate & PDF Inspection',
    description: 'Enforces human confirmation checkbox and PDF inspection before enabling quotation dispatch via Zoho Mail and WhatsApp.',
    status: 'ACTIVE',
    version: 'v6.0',
    added_date: '2026-09-15',
    last_updated: '2026-09-15T18:00:00Z',
    demo_route: '/dashboard/quotations',
    demo_enabled: true,
    notes: 'Commercial safety gate preventing unverified proposal dispatches.',
  },
  {
    id: 'FEAT-INT-013',
    module: 'Accounting & Integrations',
    feature_name: '13-Tab TallyPrime 7+ Integration Center',
    description: 'Bi-directional synchronization queue with native TallyPrime 7+ JSON envelope generator and diagnostic bridge status checking.',
    status: 'ACTIVE',
    version: 'v6.0',
    added_date: '2026-09-15',
    last_updated: '2026-09-15T18:00:00Z',
    demo_route: '/dashboard/tally',
    demo_enabled: true,
    notes: 'Supports Sales, Purchases, Receipts, Payments, and Masters sync.',
  },
  {
    id: 'FEAT-PROJ-014',
    module: 'Turnkey Execution Engine',
    feature_name: 'Turnkey Projects Cockpit & Milestone Workflows',
    description: 'Comprehensive turnkey project tracking with role-based visibility, milestones, site deployments, and execution stages.',
    status: 'ACTIVE',
    version: 'v8.0',
    added_date: '2026-09-20',
    last_updated: '2026-09-20T12:00:00Z',
    demo_route: '/dashboard/projects',
    demo_enabled: true,
    notes: 'Powered by the Turnkey Execution Engine with full project delivery tracking.',
  },
  {
    id: 'FEAT-COMM-015',
    module: 'Commercial Operations',
    feature_name: 'Reseller Sourcing, Margin Engine & Lock Rules',
    description: 'Dynamic reseller margin calculation, procurement cost baseline, and strict lock controls preventing under-margin proposal dispatches.',
    status: 'ACTIVE',
    version: 'v9.0',
    added_date: '2026-09-22',
    last_updated: '2026-09-22T14:00:00Z',
    demo_route: '/dashboard/quotations',
    demo_enabled: true,
    notes: 'Internal margin transparency with confidential commercial visibility.',
  },
  {
    id: 'FEAT-MAIL-016',
    module: 'Integrations & Communications',
    feature_name: 'Gmail REST API Mailbox & Secure Crypto Token Vault',
    description: 'Non-destructive Gmail mailbox integration with AES-256-GCM token encryption, MIME parsing, and attachment dispatch.',
    status: 'ACTIVE',
    version: 'v9.1',
    added_date: '2026-09-24',
    last_updated: '2026-09-24T10:00:00Z',
    demo_route: '/dashboard/settings/email',
    demo_enabled: true,
    notes: 'Preserves dedicated Zoho CRM mailbox configuration while extending communication channels.',
  },
  {
    id: 'FEAT-AUDIT-017',
    module: 'Security & Governance',
    feature_name: 'Dual-Source Audit Trail & Enterprise RLS Policies',
    description: 'High-fidelity dual-source audit logging capturing all commercial, HR, and settings operations with Row-Level Security enforcement.',
    status: 'ACTIVE',
    version: 'v9.2',
    added_date: '2026-09-28',
    last_updated: '2026-09-28T16:00:00Z',
    demo_route: '/dashboard/settings/audit',
    demo_enabled: true,
    notes: 'Complete enterprise audit integrity with zero destructive SQL operations.',
  },
];
