/**
 * ICON TECH PRO ERP V8 — Unified Calling, AI Telephony & WhatsApp Integration Test Suite
 *
 * Verifies the exact architecture:
 * ICON ERP
 * │
 * ├── 📞 Human Call (salesperson's Airtel phone)
 * ├── 🤖 AI Voice Call (Airtel Business -> AI)
 * ├── 🔄 AI -> Human Transfer (salesperson's Airtel number)
 * ├── 💬 WhatsApp (text, company brochure, product catalogue, quotation PDF, invoice PDF, AI -> human handoff)
 * └── ✉ Email
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

describe('ICON TECH PRO ERP V8 — Telephony & WhatsApp Unified Communication Suite', () => {
  // Mock Store
  const callsStore = [];
  const outboxStore = [];
  const inboxStore = [];

  // Mock Customer
  const MOCK_CUSTOMER = {
    id: 'CUST-001',
    customer_name: 'T-Hub Hyderabad',
    phone: '+91 98490 12345',
    email: 'facilities@t-hub.co',
  };

  // Mock Salesperson
  const SALESPERSON_AIRTEL = {
    id: 'USR001',
    name: 'Dheeraj',
    airtel_phone: '+91 98490 00001',
    role: 'Admin / BDM',
  };

  test('1. 📞 Human Call: Initiates direct call from salesperson Airtel phone to customer', () => {
    const callSid = `CA_HUMAN_${Date.now()}`;
    const call = {
      id: `CALL-${Date.now()}`,
      call_sid: callSid,
      direction: 'OUTBOUND',
      caller_number: SALESPERSON_AIRTEL.airtel_phone,
      recipient_number: MOCK_CUSTOMER.phone,
      customer_id: MOCK_CUSTOMER.id,
      customer_name: MOCK_CUSTOMER.customer_name,
      status: 'INITIATED',
      intent_detected: 'GENERAL',
      is_salesperson_direct: true,
      provider_name: 'Airtel Business Direct Voice',
      extracted_summary: `Direct call from ${SALESPERSON_AIRTEL.name} (${SALESPERSON_AIRTEL.airtel_phone}) to ${MOCK_CUSTOMER.customer_name}`,
      created_at: new Date().toISOString(),
    };
    callsStore.push(call);

    assert.equal(call.direction, 'OUTBOUND');
    assert.equal(call.caller_number, '+91 98490 00001');
    assert.equal(call.recipient_number, '+91 98490 12345');
    assert.equal(call.is_salesperson_direct, true);
    assert.equal(call.customer_name, 'T-Hub Hyderabad');
    assert.equal(call.provider_name, 'Airtel Business Direct Voice');
  });

  test('2. 🤖 AI Voice Call: Inbound call via Airtel Business trunk connects to AI Voice Agent', () => {
    const callSid = `CA_AIRTEL_IN_${Date.now()}`;
    const call = {
      id: `CALL-${Date.now()}`,
      call_sid: callSid,
      direction: 'INBOUND',
      caller_number: MOCK_CUSTOMER.phone,
      recipient_number: '+91 40 6900 0000', // Airtel Business SIP Trunk Virtual Number
      customer_id: MOCK_CUSTOMER.id,
      customer_name: MOCK_CUSTOMER.customer_name,
      status: 'IN_PROGRESS',
      intent_detected: 'SALES_ENQUIRY',
      language: 'en',
      duration_seconds: 45,
      transcript_turns: [
        { speaker: 'CALLER', text: 'Hi, we need an urgent quotation for a 98-inch interactive display.', timestamp: new Date().toISOString() },
        { speaker: 'AI_AGENT', text: 'Welcome to ICON TECH PRO! I can certainly assist you with our 4K interactive panels. Let me gather your space requirements.', timestamp: new Date().toISOString() },
        { speaker: 'CALLER', text: 'Can I speak with Dheeraj directly to finalize pricing?', timestamp: new Date().toISOString() },
      ],
      provider_name: 'Airtel Business IQ',
      created_at: new Date().toISOString(),
    };
    callsStore.push(call);

    assert.equal(call.direction, 'INBOUND');
    assert.equal(call.provider_name, 'Airtel Business IQ');
    assert.equal(call.customer_id, 'CUST-001');
    assert.equal(call.transcript_turns.length, 3);
    assert.equal(call.intent_detected, 'SALES_ENQUIRY');
  });

  test('3. 🔄 AI → Human Transfer: Bridges AI call to salesperson Airtel number with warm handoff brief', () => {
    const activeCall = callsStore.find(c => c.direction === 'INBOUND');
    assert.ok(activeCall);

    // Warm handoff summary generated by AI
    const handoffSummary = `AI -> HUMAN WARM TRANSFER:
Caller: ${activeCall.customer_name} (${activeCall.caller_number})
Detected Intent: ${activeCall.intent_detected}
Reason: Customer requested to speak with Dheeraj directly to finalize pricing
Context: Caller requested 98-inch interactive display quotation.`;

    activeCall.transferred_to = SALESPERSON_AIRTEL.airtel_phone;
    activeCall.transferred_salesperson_name = SALESPERSON_AIRTEL.name;
    activeCall.transfer_status = 'INITIATED';
    activeCall.transfer_reason = 'Customer requested human salesperson';
    activeCall.transfer_summary = handoffSummary;
    activeCall.transcript_turns.push({
      speaker: 'AI_AGENT',
      text: `Transferring your call to our Senior Solutions Specialist at ${SALESPERSON_AIRTEL.airtel_phone}. Please hold the line while I bridge you.`,
      timestamp: new Date().toISOString(),
    });

    assert.equal(activeCall.transferred_to, '+91 98490 00001');
    assert.equal(activeCall.transferred_salesperson_name, 'Dheeraj');
    assert.equal(activeCall.transfer_status, 'INITIATED');
    assert.ok(activeCall.transfer_summary.includes('AI -> HUMAN WARM TRANSFER'));
    assert.ok(activeCall.transfer_summary.includes('+91 98490 12345'));
  });

  test('4. 💬 WhatsApp: Text message and Company Brochure PDF dispatch', () => {
    const brochureUrl = 'https://assets.icontechpro.in/brochures/ICON_TECH_PRO_Corporate_Brochure_2026.pdf';
    const outboxItem = {
      id: `OUT-${Date.now()}-1`,
      channel: 'WHATSAPP',
      recipient: MOCK_CUSTOMER.phone,
      recipient_name: MOCK_CUSTOMER.customer_name,
      customer_id: MOCK_CUSTOMER.id,
      message_body: 'Hello T-Hub Hyderabad, please find attached our comprehensive Company Brochure.',
      attachment_url: brochureUrl,
      attachment_type: 'BROCHURE',
      status: 'SENT',
      provider_name: 'Meta WhatsApp Cloud API',
      created_at: new Date().toISOString(),
    };
    outboxStore.push(outboxItem);

    assert.equal(outboxItem.channel, 'WHATSAPP');
    assert.equal(outboxItem.attachment_type, 'BROCHURE');
    assert.ok(outboxItem.attachment_url.endsWith('.pdf'));
    assert.equal(outboxItem.status, 'SENT');
  });

  test('5. 💬 WhatsApp: Product Catalogue PDF dispatch', () => {
    const catalogueUrl = 'https://assets.icontechpro.in/catalogues/ICON_Catalogue_Commercial_AV_2026.pdf';
    const outboxItem = {
      id: `OUT-${Date.now()}-2`,
      channel: 'WHATSAPP',
      recipient: MOCK_CUSTOMER.phone,
      recipient_name: MOCK_CUSTOMER.customer_name,
      customer_id: MOCK_CUSTOMER.id,
      message_body: 'Here is our latest 2026 Product Catalogue for Commercial AV solutions.',
      attachment_url: catalogueUrl,
      attachment_type: 'CATALOGUE',
      status: 'SENT',
      provider_name: 'Meta WhatsApp Cloud API',
      created_at: new Date().toISOString(),
    };
    outboxStore.push(outboxItem);

    assert.equal(outboxItem.channel, 'WHATSAPP');
    assert.equal(outboxItem.attachment_type, 'CATALOGUE');
    assert.ok(outboxItem.attachment_url.includes('Commercial_AV'));
  });

  test('6. 💬 WhatsApp: Dynamic Quotation PDF & Invoice PDF delivery with 18% GST', () => {
    // Quotation PDF
    const quoteOutbox = {
      id: `OUT-${Date.now()}-3`,
      channel: 'WHATSAPP',
      recipient: MOCK_CUSTOMER.phone,
      customer_id: MOCK_CUSTOMER.id,
      quotation_id: 'QUOT-101',
      message_body: 'Dear T-Hub, please find attached your formal quotation Q-2026-001 for ₹6,20,000 (incl. 18% GST).',
      attachment_url: 'https://documents.icontechpro.in/quotations/Q-2026-001.pdf',
      attachment_type: 'QUOTATION',
      status: 'SENT',
      created_at: new Date().toISOString(),
    };
    outboxStore.push(quoteOutbox);

    // Invoice PDF
    const invoiceOutbox = {
      id: `OUT-${Date.now()}-4`,
      channel: 'WHATSAPP',
      recipient: MOCK_CUSTOMER.phone,
      customer_id: MOCK_CUSTOMER.id,
      invoice_id: 'INV-101',
      message_body: 'Dear T-Hub, please find attached your Tax Invoice INV-2026-001 for ₹6,20,000.',
      attachment_url: 'https://documents.icontechpro.in/invoices/INV-2026-001.pdf',
      attachment_type: 'INVOICE',
      status: 'SENT',
      created_at: new Date().toISOString(),
    };
    outboxStore.push(invoiceOutbox);

    assert.equal(quoteOutbox.attachment_type, 'QUOTATION');
    assert.ok(quoteOutbox.message_body.includes('18% GST'));
    assert.equal(invoiceOutbox.attachment_type, 'INVOICE');
    assert.ok(invoiceOutbox.attachment_url.includes('INV-2026-001.pdf'));
  });

  test('7. 💬 WhatsApp AI → Human Handoff: Escalates conversation to salesperson Airtel phone', () => {
    const inboxItem = {
      id: 'INB-000099',
      channel: 'WHATSAPP',
      sender: MOCK_CUSTOMER.phone,
      sender_name: 'T-Hub Facilities Desk',
      recipient: '+91 98490 00001',
      message_body: 'We want to negotiate a 5% discount on the auditorium setup. Please connect me with the BDM.',
      customer_id: MOCK_CUSTOMER.id,
      customer_name: MOCK_CUSTOMER.customer_name,
      handoff_requested: false,
      handoff_status: 'NONE',
      received_at: new Date().toISOString(),
      created_at: new Date().toISOString(),
    };
    inboxStore.push(inboxItem);

    // Trigger AI -> Human Escalation
    inboxItem.handoff_requested = true;
    inboxItem.handoff_status = 'PENDING';
    inboxItem.assigned_salesperson_id = SALESPERSON_AIRTEL.id;
    inboxItem.assigned_salesperson_name = SALESPERSON_AIRTEL.name;
    inboxItem.assigned_salesperson_phone = SALESPERSON_AIRTEL.airtel_phone;

    assert.equal(inboxItem.handoff_requested, true);
    assert.equal(inboxItem.handoff_status, 'PENDING');
    assert.equal(inboxItem.assigned_salesperson_phone, '+91 98490 00001');
    assert.equal(inboxItem.assigned_salesperson_name, 'Dheeraj');
  });

  test('8. ✉ Email: Dispatches formal proposal with PDF attachment', () => {
    const emailOutbox = {
      id: `OUT-${Date.now()}-5`,
      channel: 'EMAIL',
      recipient: MOCK_CUSTOMER.email,
      recipient_name: MOCK_CUSTOMER.customer_name,
      customer_id: MOCK_CUSTOMER.id,
      subject: 'Commercial AV Proposal & Quotation Q-2026-001 — ICON TECH PRO',
      message_body: 'Dear T-Hub Team,\n\nPlease find attached the formal proposal and quotation.\n\nBest Regards,\nICON TECH PRO Team',
      attachment_url: 'https://documents.icontechpro.in/quotations/Q-2026-001.pdf',
      attachment_type: 'QUOTATION',
      status: 'SENT',
      provider_name: 'Resend / SMTP Gateway',
      created_at: new Date().toISOString(),
    };
    outboxStore.push(emailOutbox);

    assert.equal(emailOutbox.channel, 'EMAIL');
    assert.equal(emailOutbox.recipient, 'facilities@t-hub.co');
    assert.equal(emailOutbox.attachment_type, 'QUOTATION');
    assert.equal(emailOutbox.status, 'SENT');
  });
});
