import {
  UserStaff,
  Product,
  Enquiry,
  Quotation,
  SalesOrder,
  Invoice,
  Payment,
  Supplier,
  AuditLog,
  SiteVisitDetails,
  ServiceTicket,
  EquipmentRental,
  Dispatch,
} from '@/types/erp';
import type { Customer } from '@/types/customer';

// The 6 team members from Master Functional Specification (Section 3)
export const STAFF_MEMBERS: UserStaff[] = [
  {
    id: 'USR001',
    name: 'B V Dheeraj Reddy',
    email: 'dheeraj@icontechpro.in',
    role: 'Admin / BDM',
    phone: '+91 80999 09921',
    canViewCosts: true,
    canApprove: true,
    canManageUsers: true,
    canManageAccounts: true,
  },
  {
    id: 'USR002',
    name: 'Borra Narsimulu',
    email: 'icontechpro@gmail.com',
    role: 'Managing Director',
    phone: '+91 80999 09997',
    canViewCosts: true,
    canApprove: true,
    canManageUsers: true,
    canManageAccounts: true,
  },
  {
    id: 'USR003',
    name: 'B Vineet Babu',
    email: 'vineet@icontechpro.in',
    role: 'Sales Executive',
    phone: '+91 80999 09918',
    canViewCosts: false,
    canApprove: false,
    canManageUsers: false,
    canManageAccounts: false,
  },
  {
    id: 'USR004',
    name: 'Reshma',
    email: 'sales@icontechpro.in',
    role: 'Sales Executive',
    phone: '+91 7569909997',
    canViewCosts: false,
    canApprove: false,
    canManageUsers: false,
    canManageAccounts: false,
  },
  {
    id: 'USR005',
    name: 'Hemalath',
    email: 'accounts@icontechpro.in',
    role: 'Accounts',
    phone: '+91 8099909920',
    canViewCosts: true,
    canApprove: true,
    canManageUsers: false,
    canManageAccounts: true,
  },
  {
    id: 'USR006',
    name: 'Manisha',
    email: 'service01@icontechpro.in',
    role: 'Office Assistant',
    phone: '+91 8099909914',
    canViewCosts: false,
    canApprove: false,
    canManageUsers: false,
    canManageAccounts: false,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'ICON260001',
    customer_code: 'ICON260001',
    customer_type: 'COMPANY',
    customer_name: 'Rajesh Sharma',
    company_name: 'Swan Solutions & Services',
    contact_person: 'Rajesh Sharma',
    designation: 'IT Infrastructure Head',
    phone: '+91 98490 12345',
    alternate_phone: '+91 40 2311 4455',
    email: 'rajesh@swansolutions.in',
    billing_address: 'Plot 18, Phase 2, HITEC City, Madhapur',
    shipping_address: 'Plot 18, Phase 2, HITEC City, Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500081',
    gstin: '36AABCS1234F1Z8',
    pan: 'AABCS1234F',
    credit_limit: 500000,
    enquiry_source: 'Existing Customer',
    salesperson_id: 'USR001',
    status: 'ACTIVE',
    notes: 'Key enterprise IT client with recurring quarterly network expansions.',
    created_by: 'USR001',
    updated_by: null,
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-09-03T14:00:00Z',
  },
  {
    id: 'ICON260002',
    customer_code: 'ICON260002',
    customer_type: 'COMPANY',
    customer_name: 'Kavita Reddy',
    company_name: 'ABC Technologies Pvt Ltd',
    contact_person: 'Kavita Reddy',
    designation: 'Chief Technology Officer',
    phone: '+91 98491 23456',
    alternate_phone: null,
    email: 'kavita@abctech.com',
    billing_address: 'Road No. 12, Banjara Hills',
    shipping_address: 'Road No. 12, Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500034',
    gstin: '36AAACA9876Q1ZM',
    pan: 'AAACA9876Q',
    credit_limit: 750000,
    enquiry_source: 'Reference',
    salesperson_id: 'USR003',
    status: 'ACTIVE',
    notes: 'Corporate client upgrading Dell enterprise server infrastructure.',
    created_by: 'USR003',
    updated_by: null,
    created_at: '2026-08-20T11:00:00Z',
    updated_at: '2026-09-04T13:20:00Z',
  },
  {
    id: 'ICON260003',
    customer_code: 'ICON260003',
    customer_type: 'INDIVIDUAL',
    customer_name: 'Ravi Kumar',
    company_name: 'Ravi Kumar Residence',
    contact_person: 'Ravi Kumar',
    designation: 'Homeowner',
    phone: '+91 98492 34567',
    alternate_phone: null,
    email: 'ravikumar.hyd@gmail.com',
    billing_address: 'Plot 42, Road No. 36, Jubilee Hills',
    shipping_address: 'Plot 42, Road No. 36, Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500033',
    gstin: null,
    pan: 'BNYPK4912J',
    credit_limit: 0,
    enquiry_source: 'Website',
    salesperson_id: 'USR004',
    status: 'ACTIVE',
    notes: 'Premium residential luxury Dolby Atmos 7.2.4 Home Theater installation.',
    created_by: 'USR004',
    updated_by: null,
    created_at: '2026-08-28T14:20:00Z',
    updated_at: '2026-09-04T13:30:00Z',
  },
  {
    id: 'ICON260004',
    customer_code: 'ICON260004',
    customer_type: 'COMPANY',
    customer_name: 'Dr. Srinivas Rao',
    company_name: 'Telangana State Tech Academy',
    contact_person: 'Dr. Srinivas Rao',
    designation: 'Director of Academic Technology',
    phone: '+91 98493 45678',
    alternate_phone: '+91 40 2300 1122',
    email: 'director@tsta.gov.in',
    billing_address: 'Academic Block B, Gachibowli',
    shipping_address: 'Academic Block B, Gachibowli',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500032',
    gstin: '36AAAGT4412E1ZQ',
    pan: 'AAAGT4412E',
    credit_limit: 1500000,
    enquiry_source: 'Reference',
    salesperson_id: 'USR001',
    status: 'ACTIVE',
    notes: 'State institutional project for 3 smart interactive training rooms.',
    created_by: 'USR001',
    updated_by: null,
    created_at: '2026-09-01T09:15:00Z',
    updated_at: '2026-09-04T13:40:00Z',
  },
  {
    id: 'ICON260005',
    customer_code: 'ICON260005',
    customer_type: 'COMPANY',
    customer_name: 'Ramesh Varma',
    company_name: 'Hitech Security Solutions',
    contact_person: 'Ramesh Varma',
    designation: 'Managing Partner',
    phone: '+91 98494 56789',
    alternate_phone: null,
    email: 'ramesh@hitechsec.in',
    billing_address: 'Hitech City Main Road, Madhapur',
    shipping_address: 'Hitech City Main Road, Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500081',
    gstin: '36AABCH9921D1Z5',
    pan: 'AABCH9921D',
    credit_limit: 300000,
    enquiry_source: 'Phone',
    salesperson_id: 'USR004',
    status: 'ACTIVE',
    notes: 'System integrator partner seeking commercial CCTV and NVR equipment.',
    created_by: 'USR004',
    updated_by: null,
    created_at: '2026-09-04T13:45:00Z',
    updated_at: '2026-09-04T13:45:00Z',
  },
  {
    id: 'ICON260006',
    customer_code: 'ICON260006',
    customer_type: 'COMPANY',
    customer_name: 'Dr. Vijay Krishna',
    company_name: 'Sri Sai Hospitals & Diagnostic Center',
    contact_person: 'Dr. Vijay Krishna',
    designation: 'Medical Director',
    phone: '+91 98495 67890',
    alternate_phone: '+91 40 2305 8899',
    email: 'vijay@srisaihospitals.org',
    billing_address: 'Phase 3, KPHB Colony, Kukatpally',
    shipping_address: 'Phase 3, KPHB Colony, Kukatpally',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500072',
    gstin: '36AAGCS7712K1Z3',
    pan: 'AAGCS7712K',
    credit_limit: 600000,
    enquiry_source: 'Direct',
    salesperson_id: 'USR004',
    status: 'ACTIVE',
    notes: 'Healthcare multi-location surveillance and patient monitoring network.',
    created_by: 'USR004',
    updated_by: null,
    created_at: '2026-08-22T10:00:00Z',
    updated_at: '2026-08-28T16:00:00Z',
  },
  {
    id: 'ICON260007',
    customer_code: 'ICON260007',
    customer_type: 'COMPANY',
    customer_name: 'Suresh Nambiar',
    company_name: 'Cyber Heights Commercial Complex',
    contact_person: 'Suresh Nambiar',
    designation: 'Facility General Manager',
    phone: '+91 98496 78901',
    alternate_phone: null,
    email: 'suresh@cyberheights.in',
    billing_address: 'Road No. 2, Banjara Hills',
    shipping_address: 'Road No. 2, Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500034',
    gstin: '36AAACC3314L1Z2',
    pan: 'AAACC3314L',
    credit_limit: 1000000,
    enquiry_source: 'Existing Customer',
    salesperson_id: 'USR001',
    status: 'ACTIVE',
    notes: 'Commercial mall and IT office tower campus automation and security.',
    created_by: 'USR001',
    updated_by: null,
    created_at: '2026-08-15T09:00:00Z',
    updated_at: '2026-08-21T14:00:00Z',
  },
  {
    id: 'ICON260008',
    customer_code: 'ICON260008',
    customer_type: 'COMPANY',
    customer_name: 'Mrs. Aswini',
    company_name: 'Swan Environmental Private Limited',
    contact_person: 'Mrs. Aswini',
    designation: 'Procurement Specialist',
    phone: '9966993429',
    alternate_phone: null,
    email: 'procurement@swanenviron.com',
    billing_address: 'Swan Aalayaa, Plot 922 & 935, Road 47, Madhapur',
    shipping_address: 'Swan Aalayaa, Plot 922 & 935, Road 47, Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    state_code: '36',
    pincode: '500081',
    gstin: '36AAACS4511P1ZK',
    pan: 'AAACS4511P',
    credit_limit: 800000,
    enquiry_source: 'Direct',
    salesperson_id: 'USR003',
    status: 'ACTIVE',
    notes: 'Tender procurement for high-performance Lenovo workstations and testing equipment.',
    created_by: 'USR003',
    updated_by: null,
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T11:30:00Z',
  },
];

// Verified 4 Tier Discount Rules from Database
export const DISCOUNT_APPROVAL_RULES = [
  { role: 'Sales Executive', maxDiscountPct: 5, requiresApprovalFrom: 'BDM' },
  { role: 'BDM', maxDiscountPct: 15, requiresApprovalFrom: 'Admin / BDM' },
  { role: 'Admin / BDM', maxDiscountPct: 25, requiresApprovalFrom: 'Managing Director' },
  { role: 'Managing Director', maxDiscountPct: 100, requiresApprovalFrom: null },
];

// 22 Official Product Categories
export const PRODUCT_CATEGORIES = [
  'Projector',
  'Home Theater',
  'AV Solution',
  'Acoustic',
  'Printer',
  'Laptop & Desktop',
  'Interactive Boards',
  'CCTV',
  'Servers',
  'Board Room Solution',
  'LED',
  'Display Solution',
  'EPABX',
  'Access Points',
  'Biometric Solution',
  'Networking',
  'Software Solution',
  'UPS & Batteries',
  'Sound Systems',
  'Home Automation',
  'Installation',
  'Others',
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PRD001',
    sku: 'PROJ-BUS-01',
    name: 'Business Projector 4500 Lumens Full HD',
    category_name: 'Projector',
    brand_name: 'Epson',
    model_name: 'EB-2250U',
    unit: 'Nos.',
    purchase_price: 62000,
    selling_price: 78500,
    mrp: 85000,
    target_margin_pct: 21,
    gst_rate: 18,
    hsn_sac: '85286900',
    current_stock: 3,
    reorder_level: 2,
    is_serialized: true,
    is_service: false,
    supplier_name: 'Hyderabad AV Tech Distributors',
    purchase_depot: 'Secunderabad Depot',
    is_active: true,
  },
  {
    id: 'PRD002',
    sku: 'SRV-HDD-2.4T',
    name: '2.4TB SAS HDD 12Gbps 10K RPM 2.5" Enterprise',
    category_name: 'Servers',
    brand_name: 'Dell Enterprise',
    model_name: 'ST2400MM0159',
    unit: 'Nos.',
    purchase_price: 24500,
    selling_price: 32000,
    mrp: 36000,
    target_margin_pct: 23,
    gst_rate: 18,
    hsn_sac: '84717020',
    current_stock: 1,
    reorder_level: 2,
    is_serialized: true,
    is_service: false,
    supplier_name: 'Shree Prime Distributors',
    purchase_depot: 'Mumbai Central Hub',
    is_active: true,
  },
  {
    id: 'PRD003',
    sku: 'SRV-RAM-32G',
    name: '32GB Server RAM DDR4-3200MHz ECC Registered',
    category_name: 'Servers',
    brand_name: 'HPE',
    model_name: 'P06033-B21',
    unit: 'Nos.',
    purchase_price: 11200,
    selling_price: 15500,
    mrp: 18000,
    target_margin_pct: 27,
    gst_rate: 18,
    hsn_sac: '84733030',
    current_stock: 1,
    reorder_level: 2,
    is_serialized: true,
    is_service: false,
    supplier_name: 'Shree Prime Distributors',
    purchase_depot: 'Hyderabad Local Stock',
    is_active: true,
  },
  {
    id: 'PRD004',
    sku: 'PANEL-75-4K',
    name: '75" Interactive Flat Panel 4K with Android 13 & Stylus',
    category_name: 'Interactive Boards',
    brand_name: 'ViewSonic',
    model_name: 'IFP7550-5',
    unit: 'Nos.',
    purchase_price: 142000,
    selling_price: 185000,
    mrp: 210000,
    target_margin_pct: 23,
    gst_rate: 18,
    hsn_sac: '85285200',
    current_stock: 0,
    reorder_level: 1,
    is_serialized: true,
    is_service: false,
    supplier_name: 'EduTech Displays India',
    purchase_depot: 'Bengaluru Regional Depot',
    is_active: true,
  },
  {
    id: 'PRD005',
    sku: 'HT-AVR-7.2',
    name: '7.2 Channel 8K AV Receiver Dolby Atmos',
    category_name: 'Home Theater',
    brand_name: 'Denon',
    model_name: 'AVR-X2800H',
    unit: 'Nos.',
    purchase_price: 79000,
    selling_price: 99000,
    mrp: 115000,
    target_margin_pct: 20,
    gst_rate: 18,
    hsn_sac: '85184000',
    current_stock: 2,
    reorder_level: 1,
    is_serialized: true,
    is_service: false,
    supplier_name: 'Hyderabad AV Tech Distributors',
    purchase_depot: 'Banjara Hills Branch',
    is_active: true,
  },
  {
    id: 'PRD006',
    sku: 'CCTV-CAM-4K',
    name: '8MP 4K ColorVu IP Bullet Camera with Smart AI',
    category_name: 'CCTV',
    brand_name: 'Hikvision',
    model_name: 'DS-2CD2T87G2-LSU/SL',
    unit: 'Nos.',
    purchase_price: 6800,
    selling_price: 9200,
    mrp: 11000,
    target_margin_pct: 26,
    gst_rate: 18,
    hsn_sac: '85258900',
    current_stock: 12,
    reorder_level: 4,
    is_serialized: true,
    is_service: false,
    supplier_name: 'SecuTech Systems Hyderabad',
    purchase_depot: 'Ranigunj Security Market',
    is_active: true,
  },
  {
    id: 'PRD007',
    sku: 'NET-SW-24POE',
    name: '24-Port Gigabit Managed PoE+ Network Switch',
    category_name: 'Networking',
    brand_name: 'Cisco',
    model_name: 'CBS350-24P-4G',
    unit: 'Nos.',
    purchase_price: 38000,
    selling_price: 48500,
    mrp: 55000,
    target_margin_pct: 21,
    gst_rate: 18,
    hsn_sac: '85176290',
    current_stock: 4,
    reorder_level: 2,
    is_serialized: true,
    is_service: false,
    supplier_name: 'Metro Network Solutions',
    purchase_depot: 'Hyderabad CTC Park',
    is_active: true,
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'SUP001',
    supplier_code: 'SUP-HYD-01',
    supplier_name: 'Hyderabad AV Tech Distributors',
    contact_person: 'Srinivas V',
    phone: '+91 98480 11223',
    email: 'orders@hydavtech.in',
    gstin: '36AABCH1234F1Z8',
    pan: 'AABCH1234F',
    billing_address: 'Parklane, Secunderabad, Telangana 500003',
    city: 'Secunderabad',
    payment_terms_days: 30,
    is_active: true,
  },
  {
    id: 'SUP002',
    supplier_code: 'SUP-MUM-02',
    supplier_name: 'Shree Prime Distributors',
    contact_person: 'Mitesh Patel',
    phone: '+91 98200 44556',
    email: 'sales@shreeprime.com',
    gstin: '27AAACS9876Q1ZM',
    pan: 'AAACS9876Q',
    billing_address: 'Lamington Road, Grant Road, Mumbai 400007',
    city: 'Mumbai',
    payment_terms_days: 21,
    is_active: true,
  },
  {
    id: 'SUP003',
    supplier_code: 'SUP-BLR-03',
    supplier_name: 'EduTech Displays India',
    contact_person: 'Anil Kumar',
    phone: '+91 99800 77889',
    email: 'commercial@edutechdisplays.in',
    gstin: '29AAAGE4321P1Z5',
    pan: 'AAAGE4321P',
    billing_address: 'Indiranagar 100ft Road, Bengaluru, Karnataka 560038',
    city: 'Bengaluru',
    payment_terms_days: 45,
    is_active: true,
  },
  {
    id: 'SUP004',
    supplier_code: 'SUP-HYD-04',
    supplier_name: 'SecuTech Systems Hyderabad',
    contact_person: 'Naveen Reddy',
    phone: '+91 98495 99887',
    email: 'naveen@secutechhyd.com',
    gstin: '36AAGCS5544K1Z2',
    pan: 'AAGCS5544K',
    billing_address: 'Ranigunj, Secunderabad, Telangana 500003',
    city: 'Secunderabad',
    payment_terms_days: 15,
    is_active: true,
  },
  {
    id: 'SUP005',
    supplier_code: 'SUP-HYD-05',
    supplier_name: 'Metro Network Solutions',
    contact_person: 'Gautam Rao',
    phone: '+91 98481 33445',
    email: 'info@metronetworks.in',
    gstin: '36AAACN3322D1Z9',
    pan: 'AAACN3322D',
    billing_address: 'CTC Park, Parklane, Secunderabad, Telangana 500003',
    city: 'Secunderabad',
    payment_terms_days: 30,
    is_active: true,
  },
];

export const INITIAL_ENQUIRIES: Enquiry[] = [
  {
    id: 'ENQ260001',
    enquiry_number: 'ENQ260001',
    customer_id: 'ICON260001',
    company_name: 'Swan Solutions & Services',
    customer_name: 'Rajesh Sharma',
    customer_type: 'COMPANY',
    phone: '+91 98490 12345',
    email: 'rajesh@swansolutions.in',
    source: 'Existing Customer',
    salesperson_name: 'Dheeraj',
    product_category: 'Networking',
    requirement_summary: 'Cisco 24-Port PoE Switch and 4 Access Points setup for second floor expansion.',
    estimated_budget: 65000,
    status: 'Order done',
    follow_up_date: '2026-09-05',
    site_visit_required: false,
    created_at: '2026-09-02T11:30:00Z',
    notes: [
      {
        text: 'Customer requested quotation for Gigabit managed switch and Cat6 cabling.',
        author: 'Dheeraj',
        timestamp: '2026-09-02 11:30',
      },
      {
        text: 'Quotation QT260002 accepted. Order ORD260001 created and material reserved.',
        author: 'Dheeraj',
        timestamp: '2026-09-03 14:00',
      },
    ],
  },
  {
    id: 'ENQ260002',
    enquiry_number: 'ENQ260002',
    customer_id: 'ICON260002',
    company_name: 'ABC Technologies Pvt Ltd',
    customer_name: 'Kavita Reddy',
    customer_type: 'COMPANY',
    phone: '+91 98491 23456',
    email: 'kavita@abctech.com',
    source: 'Reference',
    salesperson_name: 'Vineet Babu',
    product_category: 'Laptop & Desktop',
    requirement_summary: '5 Commercial Desktop Core i7 workstations & Dell SAS Drives upgrade.',
    estimated_budget: 120000,
    status: 'Order done',
    follow_up_date: '2026-09-06',
    site_visit_required: false,
    created_at: '2026-09-01T10:00:00Z',
    notes: [
      {
        text: 'Initial requirement received from Kavita Reddy for Dell SAS drives and server RAM upgrade.',
        author: 'Vineet Babu',
        timestamp: '2026-09-01 10:00',
      },
      {
        text: 'Quotation QT260001 sent for ₹1,08,324. Follow-up scheduled with Kavita on payment terms.',
        author: 'Vineet Babu',
        timestamp: '2026-09-02 16:15',
      },
    ],
  },
  {
    id: 'ENQ260003',
    enquiry_number: 'ENQ260003',
    customer_id: 'ICON260003',
    customer_name: 'Ravi Kumar',
    company_name: 'Ravi Kumar Residence',
    customer_type: 'INDIVIDUAL',
    phone: '+91 98492 34567',
    email: 'ravikumar.hyd@gmail.com',
    source: 'Website',
    salesperson_name: 'Reshma',
    product_category: 'Home Theater',
    requirement_summary: 'Dedicated 7.2.4 Dolby Atmos Home Theater acoustic treatment, 4K Projector & Recliners.',
    estimated_budget: 300000,
    status: 'Quotation sent',
    follow_up_date: '2026-09-06',
    site_visit_required: true,
    site_visit: {
      required: true,
      siteAddress: 'Plot 42, Jubilee Hills, Road No 36, Hyderabad',
      roomType: 'Home Theater Basement Room',
      measurements: '22ft L x 16ft W x 10.5ft H',
      scheduledDate: '2026-09-03',
      assignedTechnician: 'Nagaraju (AV Tech)',
      notes: 'Site inspection completed. Wiring conduit in place. Client approved acoustic fabric layout.',
    },
    created_at: '2026-08-28T14:20:00Z',
  },
  {
    id: 'ENQ260004',
    enquiry_number: 'ENQ260004',
    customer_id: 'ICON260004',
    company_name: 'Telangana State Tech Academy',
    customer_name: 'Dr. Srinivas Rao',
    customer_type: 'COMPANY',
    phone: '+91 98493 45678',
    email: 'director@tsta.gov.in',
    source: 'Reference',
    salesperson_name: 'Dheeraj',
    product_category: 'Interactive Boards',
    requirement_summary: '3x 75" Interactive Flat Panels for smart training classrooms with wall mounts & OPS PC.',
    estimated_budget: 700000,
    status: 'Quotation sent',
    follow_up_date: '2026-09-07',
    site_visit_required: true,
    created_at: '2026-09-01T09:15:00Z',
  },
  {
    id: 'ENQ260005',
    enquiry_number: 'ENQ260005',
    customer_id: 'ICON260005',
    company_name: 'Hitech Security Solutions',
    customer_name: 'Ramesh Varma',
    customer_type: 'COMPANY',
    phone: '+91 98494 56789',
    email: 'ramesh@hitechsec.in',
    source: 'Phone',
    salesperson_name: 'Reshma',
    product_category: 'CCTV',
    requirement_summary: '16x 4K ColorVu IP Bullet Cameras, 32-channel NVR with 16TB Storage for IT building security.',
    estimated_budget: 150000,
    status: 'Follow up',
    follow_up_date: '2026-09-05',
    site_visit_required: true,
    created_at: '2026-09-04T13:45:00Z',
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'ICON-EST-1099',
    quotation_number: 'ICON-EST-1099',
    revision_number: 1,
    entity_code: 'ICON_TECH_PRO',
    customer_id: 'CUST-SWAN-ENV',
    customer_name: 'Mrs. Aswini',
    company_name: 'Swan Environmental Private Limited',
    customer_type: 'COMPANY',
    phone: '9966993429',
    email: 'procurement@swanenviron.com',
    address: 'Second Floor, Swami Ayyappa Co. Op. Society, Swan Aalayaa, Plot no 922 & 935, Road No. 47, SBH Officers Colony, Mega Hills, Madhapur, Hyderabad City, TELANGANA, 500081',
    dispatch_from: '7-1-62/A, FLAT NO-503, 5 TH FLOOR, AMEER ESTATE, SANJEEVA REDDY NAGAR, SANJEEVA REDDY NAGAR, Hyderabad, TELANGANA, 500038',
    salesperson_name: 'Vineet Babu',
    quotation_date: '2026-09-08',
    validity_days: 7,
    place_of_supply: '36-TELANGANA',
    items: [
      {
        product_id: null,
        product_name: 'Lenovo Neo 30t Gen 5 - i5-13420H|8GB DDR5 Sodimm|512GB SSD M.2 2280 G4 TLC OPAL|Windows OEM|KYB|Mouse|Wifi|3Y Premier Support |19.5\'\' Monitor/ add on serial port + Parallel port card',
        sku: 'LENOVO-NEO-30T-G5',
        category: 'Workstations',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 54000,
        selling_price: 69000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '-',
        total_amount: 81420,
        is_custom: true,
      },
    ],
    subtotal: 69000,
    total_discount: 0,
    taxable_amount: 69000,
    cgst_amount: 6210,
    sgst_amount: 6210,
    igst_amount: 0,
    grand_total: 81420,
    total_cost: 54000,
    margin_pct: 21.7,
    payment_terms: '100% ADVANCE PAYMENT',
    delivery_terms: 'IMMEDIATELY',
    terms_conditions: [
      'Payment : 100% ADVANCE PAYMENT',
      'Taxes : GST 18% INCLUSIVE',
      'Delivery : IMMEDIATELY',
      'Warranty : AS PER COMPANY TERMS',
      'Validity : 7 Days',
      'TRANSPORTATION AND INSTALLATION CHARGES INCLUSIVE',
    ],
    bank_details: {
      bank_name: 'IDBI Bank',
      account_holder: 'ICON TECH PRO',
      account_number: '0426653800000161',
      ifsc_code: 'IBKL0000426',
      branch: 'BANDRI COMPLEX',
    },
    include_signature: true,
    status: 'Sent',
    notes: 'Official Lenovo Workstation proposal as per client tender specifications.',
    created_at: '2026-09-08T11:30:00Z',
  },
  {
    id: 'QT260001',
    quotation_number: 'QT260001',
    revision_number: 1,
    entity_code: 'ICON_TECH_PRO',
    enquiry_id: 'ENQ260002',
    customer_id: 'ICON260002',
    company_name: 'ABC Technologies Pvt Ltd',
    customer_name: 'Kavita Reddy',
    customer_type: 'COMPANY',
    phone: '+91 98491 23456',
    email: 'kavita@abctech.com',
    address: 'Banjara Hills Road No. 12, Hyderabad, Telangana 500034',
    salesperson_name: 'Vineet Babu',
    quotation_date: '2026-09-02',
    validity_days: 15,
    items: [
      {
        product_id: 'PRD002',
        product_name: '2.4TB SAS HDD 12Gbps 10K RPM 2.5" Enterprise',
        sku: 'SRV-HDD-2.4T',
        category: 'Servers',
        unit: 'Nos.',
        quantity: 2,
        purchase_price: 24500,
        selling_price: 32000,
        discount_pct: 5,
        discount_amount: 3200,
        gst_rate: 18,
        hsn_sac: '84717020',
        total_amount: 60800,
      },
      {
        product_id: 'PRD003',
        product_name: '32GB Server RAM DDR4-3200MHz ECC Registered',
        sku: 'SRV-RAM-32G',
        category: 'Servers',
        unit: 'Nos.',
        quantity: 2,
        purchase_price: 11200,
        selling_price: 15500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '84733030',
        total_amount: 31000,
      },
    ],
    subtotal: 91800,
    total_discount: 3200,
    taxable_amount: 91800,
    cgst_amount: 8262,
    sgst_amount: 8262,
    igst_amount: 0,
    grand_total: 108324,
    total_cost: 71400,
    margin_pct: 22.2,
    payment_terms: '50% advance along with confirmed PO, 50% against delivery and installation.',
    delivery_terms: 'Immediate from ready stock within 2 business days.',
    status: 'Accepted',
    order_id: 'ORD260002',
    notes: 'Includes manufacturer warranty of 3 years and on-site hardware support.',
    created_at: '2026-09-02T16:15:00Z',
  },
  {
    id: 'QT260002',
    quotation_number: 'QT260002',
    revision_number: 1,
    entity_code: 'ICON_TECH_PRO',
    enquiry_id: 'ENQ260001',
    customer_id: 'ICON260001',
    company_name: 'Swan Solutions & Services',
    customer_name: 'Rajesh Sharma',
    customer_type: 'COMPANY',
    phone: '+91 98490 12345',
    email: 'rajesh@swansolutions.in',
    address: 'Madhapur, Hitech City, Hyderabad, Telangana 500081',
    salesperson_name: 'Dheeraj',
    quotation_date: '2026-09-03',
    validity_days: 30,
    items: [
      {
        product_id: 'PRD007',
        product_name: '24-Port Gigabit Managed PoE+ Network Switch',
        sku: 'NET-SW-24POE',
        category: 'Networking',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 38000,
        selling_price: 48500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85176290',
        total_amount: 48500,
      },
    ],
    subtotal: 48500,
    total_discount: 0,
    taxable_amount: 48500,
    cgst_amount: 4365,
    sgst_amount: 4365,
    igst_amount: 0,
    grand_total: 57230,
    total_cost: 38000,
    margin_pct: 21.6,
    payment_terms: '100% within 15 days of invoice date.',
    delivery_terms: 'Ex-Stock Hyderabad, delivered within 24 hours.',
    status: 'Accepted',
    notes: 'Includes initial rack mounting and VLAN configuration support.',
    order_id: 'ORD260001',
    created_at: '2026-09-03T11:00:00Z',
  },
  {
    id: 'QT260003',
    quotation_number: 'QT260003',
    revision_number: 1,
    entity_code: 'ICON_TECH_PRO',
    enquiry_id: 'ENQ260003',
    customer_id: 'ICON260003',
    company_name: 'Ravi Kumar Residence',
    customer_name: 'Ravi Kumar',
    customer_type: 'INDIVIDUAL',
    phone: '+91 98492 34567',
    email: 'ravikumar.hyd@gmail.com',
    address: 'Plot 42, Jubilee Hills, Hyderabad, Telangana 500033',
    salesperson_name: 'Reshma',
    quotation_date: '2026-09-04',
    validity_days: 15,
    items: [
      {
        product_id: 'PRD005',
        product_name: '7.2 Channel 8K AV Receiver Dolby Atmos',
        sku: 'HT-AVR-7.2',
        category: 'Home Theater',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 79000,
        selling_price: 99000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85184000',
        total_amount: 99000,
      },
      {
        product_id: 'PRD001',
        product_name: 'Business / Cinema Projector 4500 Lumens Full HD',
        sku: 'PROJ-BUS-01',
        category: 'Projector',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 62000,
        selling_price: 78500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85286900',
        total_amount: 78500,
      },
    ],
    subtotal: 177500,
    total_discount: 0,
    taxable_amount: 177500,
    cgst_amount: 15975,
    sgst_amount: 15975,
    igst_amount: 0,
    grand_total: 209450,
    total_cost: 141000,
    margin_pct: 20.6,
    payment_terms: '50% advance booking, 40% upon equipment arrival, 10% on completion.',
    delivery_terms: 'Installation and room calibration within 5 working days.',
    status: 'Sent',
    notes: 'Proposal generated following 03-Sep basement inspection. Sent via WhatsApp and email.',
    created_at: '2026-09-04T13:30:00Z',
  },
  {
    id: 'QT260004',
    quotation_number: 'QT260004',
    revision_number: 1,
    entity_code: 'ICON_TECH_PRO',
    enquiry_id: 'ENQ260004',
    customer_id: 'ICON260004',
    company_name: 'Telangana State Tech Academy',
    customer_name: 'Dr. Srinivas Rao',
    customer_type: 'COMPANY',
    phone: '+91 98493 45678',
    email: 'director@tsta.gov.in',
    address: 'Gachibowli, Hyderabad, Telangana 500032',
    salesperson_name: 'Dheeraj',
    quotation_date: '2026-09-04',
    validity_days: 30,
    items: [
      {
        product_id: 'PRD004',
        product_name: '75" Interactive Flat Panel 4K with Android 13 & Stylus',
        sku: 'PANEL-75-4K',
        category: 'Interactive Boards',
        unit: 'Nos.',
        quantity: 3,
        purchase_price: 142000,
        selling_price: 185000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85285200',
        total_amount: 555000,
      },
    ],
    subtotal: 555000,
    total_discount: 0,
    taxable_amount: 555000,
    cgst_amount: 49950,
    sgst_amount: 49950,
    igst_amount: 0,
    grand_total: 654900,
    total_cost: 426000,
    margin_pct: 23.2,
    payment_terms: 'Government / Institutional terms: 100% against delivery and installation.',
    delivery_terms: 'Direct dispatch from manufacturer depot to Gachibowli campus.',
    status: 'Sent',
    notes: 'Submitted proposal to TSTA Directorate for 3 smart classrooms.',
    created_at: '2026-09-04T13:40:00Z',
  },
];

export const INITIAL_ORDERS: SalesOrder[] = [
  {
    id: 'ORD260001',
    order_number: 'ORD260001',
    entity_code: 'ICON_TECH_PRO',
    quotation_id: 'QT260002',
    quotation_number: 'QT260002',
    customer_id: 'ICON260001',
    company_name: 'Swan Solutions & Services',
    customer_name: 'Rajesh Sharma',
    salesperson_name: 'Dheeraj',
    order_date: '2026-09-03',
    expected_delivery: '2026-09-04',
    items: [
      {
        product_id: 'PRD007',
        sku: 'NET-SW-24POE',
        product_name: '24-Port Gigabit Managed PoE+ Network Switch',
        quantity: 1,
        selling_price: 48500,
        discount_amount: 0,
        gst_rate: 18,
        total_amount: 57230,
        reserved_quantity: 1,
        dispatched_quantity: 1,
      },
    ],
    total_amount: 57230,
    status: 'Confirmed',
    material_status: 'Stock Reserved',
    dispatch_status: 'Dispatched',
    invoice_id: 'INV260001',
    courier_tracking: 'Professional Couriers HYD-892109',
    created_at: '2026-09-03T14:00:00Z',
  },
  {
    id: 'ORD260002',
    order_number: 'ORD260002',
    entity_code: 'ICON_TECH_PRO',
    quotation_id: 'QT260001',
    quotation_number: 'QT260001',
    customer_id: 'ICON260002',
    company_name: 'ABC Technologies Pvt Ltd',
    customer_name: 'Kavita Reddy',
    salesperson_name: 'Vineet Babu',
    order_date: '2026-09-04',
    expected_delivery: '2026-09-06',
    items: [
      {
        product_id: 'PRD002',
        sku: 'SRV-HDD-2.4T',
        product_name: '2.4TB SAS HDD 12Gbps 10K RPM 2.5" Enterprise',
        quantity: 2,
        selling_price: 32000,
        discount_amount: 3200,
        gst_rate: 18,
        total_amount: 71744,
        reserved_quantity: 2,
      },
      {
        product_id: 'PRD003',
        sku: 'SRV-RAM-32G',
        product_name: '32GB Server RAM DDR4-3200MHz ECC Registered',
        quantity: 2,
        selling_price: 15500,
        discount_amount: 0,
        gst_rate: 18,
        total_amount: 36580,
        reserved_quantity: 2,
      },
    ],
    total_amount: 108324,
    status: 'Confirmed',
    material_status: 'Stock Reserved',
    dispatch_status: 'Not Dispatched',
    invoice_id: 'INV260002',
    courier_tracking: 'Local Handover Scheduled for Tomorrow',
    created_at: '2026-09-04T13:20:00Z',
  },
  {
    id: 'ORD260003',
    order_number: 'ORD260003',
    entity_code: 'ICON_TECH_PRO',
    customer_id: 'ICON260006',
    company_name: 'Sri Sai Hospitals & Diagnostic Center',
    customer_name: 'Dr. Vijay Krishna',
    salesperson_name: 'Reshma',
    order_date: '2026-08-25',
    expected_delivery: '2026-08-28',
    items: [
      {
        product_id: 'PRD006',
        sku: 'CCTV-CAM-4K',
        product_name: '8MP 4K ColorVu IP Bullet Camera with Smart AI',
        quantity: 8,
        selling_price: 9200,
        discount_amount: 0,
        gst_rate: 18,
        total_amount: 86848,
        reserved_quantity: 8,
        dispatched_quantity: 8,
      },
    ],
    total_amount: 86848,
    status: 'Confirmed',
    material_status: 'In Stock',
    dispatch_status: 'Installed & Handed Over',
    invoice_id: 'INV260003',
    courier_tracking: 'Direct Hand Delivery & Installation by Icon Tech Pro Team',
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'ORD260004',
    order_number: 'ORD260004',
    entity_code: 'ICON_TECH_PRO',
    customer_id: 'ICON260007',
    company_name: 'Cyber Heights Commercial Complex',
    customer_name: 'Suresh Nambiar',
    salesperson_name: 'Dheeraj',
    order_date: '2026-08-18',
    expected_delivery: '2026-08-21',
    items: [
      {
        product_id: 'PRD006',
        sku: 'CCTV-CAM-4K',
        product_name: '8MP 4K ColorVu IP Bullet Camera with Smart AI',
        quantity: 12,
        selling_price: 9200,
        discount_amount: 5520,
        gst_rate: 18,
        total_amount: 123758,
      },
      {
        product_id: 'PRD007',
        sku: 'NET-SW-24POE',
        product_name: '24-Port Gigabit Managed PoE+ Network Switch',
        quantity: 1,
        selling_price: 48500,
        discount_amount: 0,
        gst_rate: 18,
        total_amount: 57230,
      },
    ],
    total_amount: 180988,
    status: 'Confirmed',
    material_status: 'In Stock',
    dispatch_status: 'Installed & Handed Over',
    invoice_id: 'INV260004',
    courier_tracking: 'Hand delivered & Commissioned at Banjara Hills Site',
    created_at: '2026-08-18T15:00:00Z',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'INV260001',
    invoice_number: 'INV260001',
    invoice_type: 'TAX_INVOICE',
    entity_code: 'ICON_TECH_PRO',
    order_id: 'ORD260001',
    order_number: 'ORD260001',
    customer_id: 'ICON260001',
    company_name: 'Swan Solutions & Services',
    customer_name: 'Rajesh Sharma',
    gstin: '36AABCS1234F1Z8',
    address: 'Madhapur, Hitech City, Hyderabad, Telangana 500081',
    invoice_date: '2026-09-03',
    due_date: '2026-09-18',
    items: [
      {
        description: '24-Port Gigabit Managed PoE+ Network Switch (Cisco CBS350-24P-4G)',
        hsn_code: '85176290',
        quantity: 1,
        unit: 'Nos.',
        rate: 48500,
        gst_rate: 18,
        gst_amount: 8730,
        total_amount: 57230,
      },
    ],
    subtotal: 48500,
    cgst_amount: 4365,
    sgst_amount: 4365,
    igst_amount: 0,
    gst_amount: 8730,
    grand_total: 57230,
    paid_amount: 25000,
    balance_amount: 32230,
    status: 'Partially Paid',
    created_by_name: 'Hemalatha',
    created_at: '2026-09-03T15:30:00Z',
  },
  {
    id: 'INV260002',
    invoice_number: 'INV260002',
    invoice_type: 'TAX_INVOICE',
    entity_code: 'ICON_TECH_PRO',
    order_id: 'ORD260002',
    order_number: 'ORD260002',
    customer_id: 'ICON260002',
    company_name: 'ABC Technologies Pvt Ltd',
    customer_name: 'Kavita Reddy',
    gstin: '36AAACA9876Q1ZM',
    address: 'Banjara Hills Road No. 12, Hyderabad, Telangana 500034',
    invoice_date: '2026-09-04',
    due_date: '2026-09-19',
    items: [
      {
        description: '2.4TB SAS HDD 12Gbps 10K RPM 2.5" Enterprise',
        hsn_code: '84717020',
        quantity: 2,
        unit: 'Nos.',
        rate: 30400,
        gst_rate: 18,
        gst_amount: 10944,
        total_amount: 71744,
      },
      {
        description: '32GB Server RAM DDR4-3200MHz ECC Registered',
        hsn_code: '84733030',
        quantity: 2,
        unit: 'Nos.',
        rate: 15500,
        gst_rate: 18,
        gst_amount: 5580,
        total_amount: 36580,
      },
    ],
    subtotal: 91800,
    cgst_amount: 8262,
    sgst_amount: 8262,
    igst_amount: 0,
    gst_amount: 16524,
    grand_total: 108324,
    paid_amount: 54162,
    balance_amount: 54162,
    status: 'Partially Paid',
    created_by_name: 'Hemalatha',
    created_at: '2026-09-04T13:25:00Z',
  },
  {
    id: 'INV260003',
    invoice_number: 'INV260003',
    invoice_type: 'TAX_INVOICE',
    entity_code: 'ICON_TECH_PRO',
    order_id: 'ORD260003',
    order_number: 'ORD260003',
    customer_id: 'ICON260006',
    company_name: 'Sri Sai Hospitals & Diagnostic Center',
    customer_name: 'Dr. Vijay Krishna',
    gstin: '36AAGCS7712K1Z3',
    address: 'KPHB Colony Phase 3, Kukatpally, Hyderabad, Telangana 500072',
    invoice_date: '2026-08-27',
    due_date: '2026-09-11',
    items: [
      {
        description: '8MP 4K ColorVu IP Bullet Camera with Smart AI (Hikvision DS-2CD2T87G2)',
        hsn_code: '85258900',
        quantity: 8,
        unit: 'Nos.',
        rate: 9200,
        gst_rate: 18,
        gst_amount: 13248,
        total_amount: 86848,
      },
    ],
    subtotal: 73600,
    cgst_amount: 6624,
    sgst_amount: 6624,
    igst_amount: 0,
    gst_amount: 13248,
    grand_total: 86848,
    paid_amount: 86848,
    balance_amount: 0,
    status: 'Paid',
    created_by_name: 'Hemalatha',
    created_at: '2026-08-27T11:00:00Z',
  },
  {
    id: 'INV260004',
    invoice_number: 'INV260004',
    invoice_type: 'TAX_INVOICE',
    entity_code: 'ICON_TECH_PRO',
    order_id: 'ORD260004',
    order_number: 'ORD260004',
    customer_id: 'ICON260007',
    company_name: 'Cyber Heights Commercial Complex',
    customer_name: 'Suresh Nambiar',
    gstin: '36AAACN5543D1Z2',
    address: 'Road No. 2, Banjara Hills, Hyderabad, Telangana 500034',
    invoice_date: '2026-08-20',
    due_date: '2026-09-05',
    items: [
      {
        description: '8MP 4K ColorVu IP Bullet Camera with Smart AI (12 Units)',
        hsn_code: '85258900',
        quantity: 12,
        unit: 'Nos.',
        rate: 8740,
        gst_rate: 18,
        gst_amount: 18878,
        total_amount: 123758,
      },
      {
        description: '24-Port Gigabit Managed PoE+ Network Switch',
        hsn_code: '85176290',
        quantity: 1,
        unit: 'Nos.',
        rate: 48500,
        gst_rate: 18,
        gst_amount: 8730,
        total_amount: 57230,
      },
    ],
    subtotal: 153380,
    cgst_amount: 13804,
    sgst_amount: 13804,
    igst_amount: 0,
    gst_amount: 27608,
    grand_total: 180988,
    paid_amount: 180988,
    balance_amount: 0,
    status: 'Paid',
    created_by_name: 'Hemalatha',
    created_at: '2026-08-20T16:00:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'PAY260001',
    payment_number: 'PAY260001',
    invoice_id: 'INV260001',
    invoice_number: 'INV260001',
    customer_name: 'Rajesh Sharma',
    company_name: 'Swan Solutions & Services',
    amount: 25000,
    mode: 'UPI',
    reference_number: 'UPI/HDFC/6245890123/Advance',
    payment_date: '2026-09-03',
    notes: 'Advance part-payment received via UPI transfer.',
    recorded_by_name: 'Hemalatha',
    created_at: '2026-09-03T16:00:00Z',
  },
  {
    id: 'PAY260002',
    payment_number: 'PAY260002',
    invoice_id: 'INV260002',
    invoice_number: 'INV260002',
    customer_name: 'Kavita Reddy',
    company_name: 'ABC Technologies Pvt Ltd',
    amount: 54162,
    mode: 'Bank Transfer',
    reference_number: 'HDFCN26090481239',
    payment_date: '2026-09-04',
    notes: '50% advance against PO confirmation for Dell SAS & RAM upgrade.',
    recorded_by_name: 'Hemalatha',
    created_at: '2026-09-04T13:22:00Z',
  },
];

export const INITIAL_DISPATCHES: Dispatch[] = [
  {
    id: 'DSP260001',
    dispatch_number: 'DSP260001',
    delivery_challan_number: 'DC260001',
    order_number: 'ORD260001',
    invoice_number: 'INV260001',
    customer_name: 'Swan Solutions & Services',
    shipping_address: 'Madhapur, Hitech City, Hyderabad, Telangana 500081',
    transporter_name: 'Professional Couriers',
    vehicle_number: 'TS-09-UB-4412',
    eway_bill_number: 'EWB-361092817263',
    status: 'Dispatched',
    dispatched_by_name: 'Dheeraj',
    dispatch_date: '2026-09-04T10:00:00Z',
    created_at: '2026-09-04T10:00:00Z',
  },
];

export const INITIAL_SERVICE_TICKETS: ServiceTicket[] = [
  {
    id: 'SRV260001',
    ticket_number: 'SRV260001',
    entity_code: 'ICON_TECH_PRO',
    customer_id: 'ICON260006',
    customer_name: 'Sri Sai Hospitals',
    product_name: 'Hikvision 4K IP Camera #4',
    serial_number: 'HIK-CAM-4K-00918',
    complaint_description: 'Night vision IR LED flickering intermittently during low-light hours.',
    priority: 'Medium',
    assigned_technician_name: 'Nagaraju',
    status: 'In Progress',
    service_charge: 1500,
    created_at: '2026-09-02T14:30:00Z',
  },
  {
    id: 'SRV260002',
    ticket_number: 'SRV260002',
    entity_code: 'ICON_TECH_PRO',
    customer_id: 'ICON260007',
    customer_name: 'Cyber Heights Complex',
    product_name: 'Cisco PoE Switch 24-Port',
    serial_number: 'CSCO-SW-24P-8819',
    complaint_description: 'Port 7 and 8 not providing PoE power to connected biometric device.',
    priority: 'High',
    assigned_technician_name: 'Dheeraj',
    status: 'Resolved',
    resolution_details: 'Re-crimped RJ45 connectors and re-assigned PoE budget in switch firmware.',
    service_charge: 0,
    created_at: '2026-08-30T09:00:00Z',
  },
];

export const INITIAL_RENTALS: EquipmentRental[] = [
  {
    id: 'RNT260001',
    rental_number: 'RNT260001',
    entity_code: 'ICON_TECH_PRO',
    customer_id: 'ICON260002',
    customer_name: 'ABC Technologies Pvt Ltd',
    product_name: 'Epson 4500 Lumens Full HD Projector + Tripod Screen',
    serial_number: 'EPS-PROJ-DEMO-01',
    start_date: '2026-09-05',
    end_date: '2026-09-07',
    security_deposit: 15000,
    rental_fee: 4500,
    status: 'Active',
    created_at: '2026-09-04T12:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD006',
    timestamp: '2026-09-04 13:45:10',
    user_name: 'Reshma (Sales Executive)',
    action: 'LOG_LEAD',
    module: 'Leads',
    details: 'Logged fresh inbound CCTV requirement ENQ260005 for Hitech Security Solutions (ICON260005)',
  },
  {
    id: 'AUD005',
    timestamp: '2026-09-04 13:40:00',
    user_name: 'Dheeraj (Admin / BDM)',
    action: 'CREATE_QUOTATION',
    module: 'Quotations',
    details: 'Generated Quotation QT260004 for 3x 75" ViewSonic Interactive Panels for TSTA (₹6,54,900)',
  },
  {
    id: 'AUD004',
    timestamp: '2026-09-04 13:30:15',
    user_name: 'Reshma (Sales Executive)',
    action: 'CREATE_QUOTATION',
    module: 'Quotations',
    details: 'Issued Home Theater proposal QT260003 for Ravi Kumar (₹2,09,450) and sent via WhatsApp',
  },
  {
    id: 'AUD003',
    timestamp: '2026-09-04 13:22:00',
    user_name: 'Hemalatha (Accounts)',
    action: 'RECORD_PAYMENT',
    module: 'Accounts',
    details: 'Recorded NEFT advance PAY260002 of ₹54,162 against Invoice INV260002 (ABC Technologies)',
  },
  {
    id: 'AUD002',
    timestamp: '2026-09-04 13:20:00',
    user_name: 'Vineet Babu (BDM)',
    action: 'CONFIRM_ORDER',
    module: 'Orders',
    details: 'Converted Quotation QT260001 to Confirmed Order ORD260002 for ABC Technologies (₹1,08,324)',
  },
  {
    id: 'AUD001',
    timestamp: '2026-09-04 13:10:00',
    user_name: 'Dheeraj (Admin / BDM)',
    action: 'FOLLOW_UP_LEAD',
    module: 'Leads',
    details: 'Followed up with Rajesh Sharma (Swan Solutions) confirming delivery via Professional Couriers HYD-892109',
  },
];

export interface SolutionBundleItem {
  sku: string;
  product_name: string;
  category: string;
  unit: string;
  quantity: number;
  purchase_price: number;
  selling_price: number;
  discount_pct: number;
  discount_amount: number;
  gst_rate: number;
  hsn_sac: string;
  total_amount: number;
  is_custom: boolean;
}

export interface SolutionBundle {
  id: string;
  name: string;
  category: string;
  description: string;
  items: SolutionBundleItem[];
}

export const SOLUTION_BUNDLES: SolutionBundle[] = [
  {
    id: 'BUNDLE-SMART-CLASSROOM',
    name: 'Smart Classroom Interactive Suite',
    category: 'Interactive Boards',
    description: 'Complete digital classroom package: 75" 4K Interactive Flat Panel with OPS, 4500 Lumens Projector, and PoE Managed Switch',
    items: [
      {
        sku: 'PANEL-75-4K',
        product_name: '75" Interactive Flat Panel 4K with Android 13 & Stylus',
        category: 'Interactive Boards',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 142000,
        selling_price: 185000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85285200',
        total_amount: 185000 * 1.18,
        is_custom: false,
      },
      {
        sku: 'PROJ-BUS-01',
        product_name: 'Business Projector 4500 Lumens Full HD',
        category: 'Projector',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 62000,
        selling_price: 78500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85286900',
        total_amount: 78500 * 1.18,
        is_custom: false,
      },
      {
        sku: 'NET-SW-24POE',
        product_name: '24-Port Gigabit Managed PoE+ Network Switch',
        category: 'Networking',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 38000,
        selling_price: 48500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85176290',
        total_amount: 48500 * 1.18,
        is_custom: false,
      },
      {
        sku: 'SRV-INSTALL',
        product_name: 'Turnkey Site Installation, Cabling, Bracket Mount & Testing',
        category: 'Services',
        unit: 'Set',
        quantity: 1,
        purchase_price: 5000,
        selling_price: 12000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '998719',
        total_amount: 12000 * 1.18,
        is_custom: true,
      }
    ],
  },
  {
    id: 'BUNDLE-BOARDROOM-AV',
    name: 'Executive Boardroom AV Solution',
    category: 'Board Room Solution',
    description: 'High-end corporate boardroom setup: 4500L Full HD Projector, Denon 7.2 AV Receiver, and Cisco 24-Port PoE Switch',
    items: [
      {
        sku: 'PROJ-BUS-01',
        product_name: 'Business Projector 4500 Lumens Full HD',
        category: 'Projector',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 62000,
        selling_price: 78500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85286900',
        total_amount: 78500 * 1.18,
        is_custom: false,
      },
      {
        sku: 'HT-AVR-7.2',
        product_name: '7.2 Channel 8K AV Receiver Dolby Atmos',
        category: 'Home Theater',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 79000,
        selling_price: 99000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85184000',
        total_amount: 99000 * 1.18,
        is_custom: false,
      },
      {
        sku: 'NET-SW-24POE',
        product_name: '24-Port Gigabit Managed PoE+ Network Switch',
        category: 'Networking',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 38000,
        selling_price: 48500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85176290',
        total_amount: 48500 * 1.18,
        is_custom: false,
      },
      {
        sku: 'SRV-INSTALL',
        product_name: 'Turnkey Site Installation, Cabling, Bracket Mount & Testing',
        category: 'Services',
        unit: 'Set',
        quantity: 1,
        purchase_price: 5000,
        selling_price: 15000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '998719',
        total_amount: 15000 * 1.18,
        is_custom: true,
      }
    ],
  },
  {
    id: 'BUNDLE-IP-CCTV',
    name: 'Enterprise IP Surveillance (8-Camera Kit)',
    category: 'CCTV',
    description: 'High definition 4K ColorVu IP CCTV setup with 8 cameras, enterprise SAS storage, and 24-Port PoE Switch',
    items: [
      {
        sku: 'CCTV-CAM-4K',
        product_name: '8MP 4K ColorVu IP Bullet Camera with Smart AI',
        category: 'CCTV',
        unit: 'Nos.',
        quantity: 8,
        purchase_price: 6800,
        selling_price: 9200,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85258900',
        total_amount: 8 * 9200 * 1.18,
        is_custom: false,
      },
      {
        sku: 'SRV-HDD-2.4T',
        product_name: '2.4TB SAS HDD 12Gbps 10K RPM 2.5" Enterprise',
        category: 'Servers',
        unit: 'Nos.',
        quantity: 2,
        purchase_price: 24500,
        selling_price: 32000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '84717020',
        total_amount: 2 * 32000 * 1.18,
        is_custom: false,
      },
      {
        sku: 'NET-SW-24POE',
        product_name: '24-Port Gigabit Managed PoE+ Network Switch',
        category: 'Networking',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 38000,
        selling_price: 48500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85176290',
        total_amount: 48500 * 1.18,
        is_custom: false,
      },
      {
        sku: 'SRV-INSTALL',
        product_name: 'CCTV Cabling, Camera Mounting, Termination & NVR Configuration',
        category: 'Services',
        unit: 'Job',
        quantity: 1,
        purchase_price: 8000,
        selling_price: 18000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '998719',
        total_amount: 18000 * 1.18,
        is_custom: true,
      }
    ],
  },
  {
    id: 'BUNDLE-HOME-THEATER',
    name: 'Home Theater 7.2 Cinema Package',
    category: 'Home Theater',
    description: 'Premium home theater audio-visual setup: Denon 7.2 8K AVR and Full HD Projector with acoustic calibration',
    items: [
      {
        sku: 'HT-AVR-7.2',
        product_name: '7.2 Channel 8K AV Receiver Dolby Atmos',
        category: 'Home Theater',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 79000,
        selling_price: 99000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85184000',
        total_amount: 99000 * 1.18,
        is_custom: false,
      },
      {
        sku: 'PROJ-BUS-01',
        product_name: 'Business Projector 4500 Lumens Full HD',
        category: 'Projector',
        unit: 'Nos.',
        quantity: 1,
        purchase_price: 62000,
        selling_price: 78500,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '85286900',
        total_amount: 78500 * 1.18,
        is_custom: false,
      },
      {
        sku: 'SRV-INSTALL',
        product_name: 'Home Cinema Acoustic Calibration, Ceiling Rigging & Speaker Tuning',
        category: 'Services',
        unit: 'Set',
        quantity: 1,
        purchase_price: 6000,
        selling_price: 16000,
        discount_pct: 0,
        discount_amount: 0,
        gst_rate: 18,
        hsn_sac: '998719',
        total_amount: 16000 * 1.18,
        is_custom: true,
      }
    ],
  },
];
